title: ParkSungmin
email: byulparan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  difficult
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.  
baseurl: "" 
url: "https://byulparan.github.io" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

