title: ParkSungmin
email: byulparan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
	description?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://byulparan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
<!-- twitter_username: jekyllrb -->
<!-- github_username:  jekyll -->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

