title: ParkSungmin
email: byulparan@gmail.com
description: -> Development & Technical Training
asdfasdfsdflkasdjfla
asdfkjaskldfjalskdfj
asdkfjaskldfjklasdjf
asdfjalskdjflkasdjflkasdjf
asdfkjasdlfkjasdlkfj
baseurl: "" 
url: "https://byulparan.github.io" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

